'use client';

import { useCallback, useEffect, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, ArrowLeft, ChevronLeft, ChevronRight, Lightbulb, Monitor, Smartphone, X, ZoomIn } from 'lucide-react';
import { useStore } from '../../context/StoreContext';
import styles from './HowToBookGuide.module.css';

/* Screenshots are generated by scripts/capture-how-to-book.mjs */
const SHOT_SIZE = {
  desktop: { width: 1440, height: 900 },
  mobile: { width: 780, height: 1688 },
};
const shotSrc = (lang, view, index) => `/images/how-to-book/${lang}/${view}/step-${String(index + 1).padStart(2, '0')}.jpg`;
const pad = (n) => String(n).padStart(2, '0');

export default function HowToBookGuide() {
  const { t, lang } = useStore();
  const g = t.howToBook;
  const isAr = lang === 'ar';
  const [view, setView] = useState('desktop');
  const [zoomed, setZoomed] = useState(null); // index of the enlarged step

  // Phones see the mobile screenshots first
  useEffect(() => {
    if (window.matchMedia('(max-width: 768px)').matches) setView('mobile');
  }, []);

  const closeZoom = useCallback(() => setZoomed(null), []);
  const stepZoom = useCallback((dir) => {
    setZoomed((i) => (i === null ? i : (i + dir + g.steps.length) % g.steps.length));
  }, [g.steps.length]);

  useEffect(() => {
    if (zoomed === null) return undefined;
    const onKey = (e) => {
      if (e.key === 'Escape') closeZoom();
      if (e.key === 'ArrowRight') stepZoom(isAr ? -1 : 1);
      if (e.key === 'ArrowLeft') stepZoom(isAr ? 1 : -1);
    };
    document.body.style.overflow = 'hidden';
    window.addEventListener('keydown', onKey);
    return () => {
      document.body.style.overflow = '';
      window.removeEventListener('keydown', onKey);
    };
  }, [zoomed, closeZoom, stepZoom, isAr]);

  const size = SHOT_SIZE[view];
  const Forward = isAr ? ArrowLeft : ArrowRight;

  return (
    <div className={styles.page} dir={isAr ? 'rtl' : 'ltr'}>
      {/* Header */}
      <header className={styles.hero}>
        <div className="container">
          <nav className={styles.breadcrumb} aria-label="Breadcrumb">
            <Link href="/">{t.nav.home}</Link>
            <span aria-hidden="true">/</span>
            <span>{g.breadcrumb}</span>
          </nav>
          <span className={styles.eyebrow}>{g.eyebrow}</span>
          <h1 className={styles.title}>{g.title}</h1>
          <p className={styles.subtitle}>{g.subtitle}</p>

          {/* Step shortcuts */}
          <ol className={styles.stepNav}>
            {g.steps.map((s, i) => (
              <li key={i}>
                <a href={`#step-${i + 1}`} className={styles.stepNavLink}>
                  <span className={styles.stepNavNum}>{pad(i + 1)}</span>
                  <span className={styles.stepNavText}>{s.title}</span>
                </a>
              </li>
            ))}
          </ol>
        </div>
      </header>

      {/* Desktop / mobile screenshots switch */}
      <div className={styles.toolbar}>
        <div className={styles.viewToggle} role="group" aria-label={g.viewToggleLabel}>
          <button
            type="button"
            className={`${styles.viewBtn} ${view === 'desktop' ? styles.viewBtnActive : ''}`}
            aria-pressed={view === 'desktop'}
            onClick={() => setView('desktop')}
          >
            <Monitor size={15} /> {g.viewDesktop}
          </button>
          <button
            type="button"
            className={`${styles.viewBtn} ${view === 'mobile' ? styles.viewBtnActive : ''}`}
            aria-pressed={view === 'mobile'}
            onClick={() => setView('mobile')}
          >
            <Smartphone size={15} /> {g.viewMobile}
          </button>
        </div>
      </div>

      {/* Steps timeline */}
      <ol className={`container ${styles.timeline}`}>
        {g.steps.map((s, i) => (
          <li
            key={i}
            id={`step-${i + 1}`}
            className={`${styles.step} ${i % 2 === 1 ? styles.stepFlip : ''} ${view === 'mobile' ? styles.stepMobile : ''}`}
          >
            <div className={styles.marker} aria-hidden="true">{pad(i + 1)}</div>

            <div className={styles.text}>
              <div className={styles.stepLabelRow}>
                <span className={styles.stepLabel}>{g.stepLabel} {pad(i + 1)}</span>
                {s.optional && <span className={styles.optional}>{g.optional}</span>}
              </div>
              <h2 className={styles.stepTitle}>{s.title}</h2>
              <p className={styles.stepDesc}>{s.desc}</p>
              {s.tip && (
                <div className={styles.tip}>
                  <Lightbulb size={16} className={styles.tipIcon} />
                  <p><strong>{g.tip}:</strong> {s.tip}</p>
                </div>
              )}
            </div>

            <button
              type="button"
              className={`${styles.shot} ${view === 'mobile' ? styles.shotPhone : styles.shotBrowser}`}
              onClick={() => setZoomed(i)}
              aria-label={`${s.title} — ${g.zoomHint}`}
            >
              {view === 'desktop' && (
                <span className={styles.browserBar} aria-hidden="true"><i /><i /><i /></span>
              )}
              <Image
                src={shotSrc(lang, view, i)}
                alt={`${g.stepLabel} ${i + 1}: ${s.title}`}
                width={size.width}
                height={size.height}
                sizes={view === 'mobile' ? '300px' : '(max-width: 900px) 100vw, 640px'}
                className={styles.shotImg}
                loading={i < 2 ? 'eager' : 'lazy'}
              />
              <span className={styles.zoomBadge} aria-hidden="true"><ZoomIn size={14} /> {g.zoomHint}</span>
            </button>
          </li>
        ))}
      </ol>

      {/* Call to action */}
      <section className={styles.cta}>
        <div className="container">
          <h2 className={styles.ctaTitle}>{g.ctaTitle}</h2>
          <p className={styles.ctaDesc}>{g.ctaDesc}</p>
          <Link href="/collections" className={styles.ctaBtn}>
            <span>{g.ctaBtn}</span>
            <Forward size={16} strokeWidth={1.5} />
          </Link>
          <p className={styles.help}>
            {g.helpText}{' '}
            <Link href="/#faq">{g.faqLink}</Link>
            <span aria-hidden="true"> · </span>
            <Link href="/contact">{g.contactLink}</Link>
          </p>
        </div>
      </section>

      {/* Lightbox */}
      {zoomed !== null && (
        <div className={styles.lightbox} onClick={closeZoom} role="dialog" aria-modal="true" aria-label={g.steps[zoomed].title}>
          <button type="button" className={styles.lbClose} onClick={closeZoom} aria-label={g.close}><X size={22} /></button>
          <button
            type="button"
            className={`${styles.lbNav} ${styles.lbPrev}`}
            onClick={(e) => { e.stopPropagation(); stepZoom(-1); }}
            aria-label="Previous"
          >
            {isAr ? <ChevronRight size={26} /> : <ChevronLeft size={26} />}
          </button>
          <figure className={styles.lbFigure} onClick={(e) => e.stopPropagation()}>
            <Image
              src={shotSrc(lang, view, zoomed)}
              alt={g.steps[zoomed].title}
              width={size.width}
              height={size.height}
              className={`${styles.lbImg} ${view === 'mobile' ? styles.lbImgPhone : ''}`}
            />
            <figcaption className={styles.lbCaption}>
              <span>{g.stepLabel} {pad(zoomed + 1)}</span> {g.steps[zoomed].title}
            </figcaption>
          </figure>
          <button
            type="button"
            className={`${styles.lbNav} ${styles.lbNext}`}
            onClick={(e) => { e.stopPropagation(); stepZoom(1); }}
            aria-label="Next"
          >
            {isAr ? <ChevronLeft size={26} /> : <ChevronRight size={26} />}
          </button>
        </div>
      )}
    </div>
  );
}
